<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Entry Ad</name>
   <tag></tag>
   <elementGuidId>951bbd67-0512-4af5-80ee-40939d3c2f07</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content']/ul/li[15]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2e654e32-2d60-4e8a-94ac-8fd95de7f1fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/entry_ad</value>
      <webElementGuid>e5b71925-36a9-4b50-808f-67c4bf9bc26d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Entry Ad</value>
      <webElementGuid>70651fa2-a722-44a6-aa4c-0e5de978e4cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/ul[1]/li[15]/a[1]</value>
      <webElementGuid>fb42c86e-e12d-483f-822d-4d3501b16db0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/ul/li[15]/a</value>
      <webElementGuid>a1eb72d2-1775-4410-916f-68d08437016d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Entry Ad')]</value>
      <webElementGuid>7c431677-df5d-434b-ba86-fe5cf3843d66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dynamic Loading'])[1]/following::a[1]</value>
      <webElementGuid>52ec12d1-8a58-4ec6-a296-8ec5cb18b976</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dynamic Controls'])[1]/following::a[2]</value>
      <webElementGuid>ffd84062-b082-4ee5-93ea-72705809a9fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Exit Intent'])[1]/preceding::a[1]</value>
      <webElementGuid>0d1eb510-46c7-485a-9572-cfd62177c495</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='File Download'])[1]/preceding::a[2]</value>
      <webElementGuid>d49a9b9c-e43a-4de0-8349-4db94e4a4618</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Entry Ad']/parent::*</value>
      <webElementGuid>b4ee94bb-ed37-4a96-9e1c-42fcf9555b01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/entry_ad')]</value>
      <webElementGuid>d4af43d3-a0a1-4fce-ae2a-b6312208ead4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[15]/a</value>
      <webElementGuid>7c8ec221-f5ca-429b-a302-957f435f3875</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/entry_ad' and (text() = 'Entry Ad' or . = 'Entry Ad')]</value>
      <webElementGuid>a23de0a1-166b-4c66-a00f-48deaafb80f7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
