<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Click for JS Alert</name>
   <tag></tag>
   <elementGuidId>4897b84f-efdc-4c20-b986-d16167ba4f59</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@onclick='jsAlert()']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1ee770a4-7a66-4d9d-8815-aa151bbf3822</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>jsAlert()</value>
      <webElementGuid>d6d18d65-2322-4aae-b41e-44dc35b2ccb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Click for JS Alert</value>
      <webElementGuid>d3c5472d-8f08-4076-ba56-da8c8a7c4686</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;example&quot;]/ul[1]/li[1]/button[1]</value>
      <webElementGuid>d482a74d-1281-4deb-a433-fba617de99c5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@onclick='jsAlert()']</value>
      <webElementGuid>cb9fa21b-c1f0-49cb-ad4c-f58510286bf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div/ul/li/button</value>
      <webElementGuid>62b28f14-4f53-4687-a230-f5b7e3b4c20e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='JavaScript Alerts'])[1]/following::button[1]</value>
      <webElementGuid>3a25d28a-98fb-4613-b4fa-1dd522e2d4d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Click for JS Confirm'])[1]/preceding::button[1]</value>
      <webElementGuid>d30fd878-6dd3-4ef9-af59-4c20fd7d8610</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Click for JS Prompt'])[1]/preceding::button[2]</value>
      <webElementGuid>f7b52cf0-e78d-476e-8ad6-bcfc0d53a832</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Click for JS Alert']/parent::*</value>
      <webElementGuid>257a6cca-34b6-45a8-b28a-b7d7f840d6a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>c7cc68cc-88d7-4d27-961f-bdae1c3e8cd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Click for JS Alert' or . = 'Click for JS Alert')]</value>
      <webElementGuid>57e79c93-e110-4d33-881c-d8a854a923f0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
